### ISSUE TITLE
Stanford-Manuscript: AttributeError: 'Dataset' object has no attribute 'value'

### ISSUE THREAD

**Issue by RaghavRao** [Stanford-STAGES/stanford-stages#32]
Has anyone run into this before? It happens right at the end, when trying to assign the score.
This was with CHP040.edf on the manuscript branch
Traceback:

```
2020-11-25 17:23:21.144521 | Predicting using: ac_rh_ls_lstm_01
Traceback (most recent call last):
  File "inf_narco_app.py", line 302, in <module>
    main(edfFile, jsonObj)
  File "inf_narco_app.py", line 124, in main
    print(narcoApp.get_diagnosis())
  File "inf_narco_app.py", line 185, in get_diagnosis
    prediction = self.get_narco_prediction()
  File "inf_narco_app.py", line 243, in get_narco_prediction
    os.path.join(gpmodels_base_path, gpmodel, gpmodel + '_fold{:02}.gpm'.format(k + 1)))
  File "/home/user/Envs/stanford-manuscript/lib/python3.6/site-packages/gpflow/saver/saver.py", line 41, in load
    encoded_target = context.serializer(context).load(pathname)
  File "/home/user/Envs/stanford-manuscript/lib/python3.6/site-packages/gpflow/saver/serializers.py", line 48, in load
    return h5file['data'].value
AttributeError: 'Dataset' object has no attribute 'value'
```

**Comment by informaton** [comment]
I have seen this issue before when the __h5py__ package is more recent than what is supported by the gpflow package.  
I'm using __h5py__ version __2.10.0__ for the manuscript branch and it only gives a deprecation warning about the 'Dataset' object's 'value' attribute.

Try downgrading your __h5py__ package.  If you are using pip, it should be `pip install h5py==2.10`

**Comment by RaghavRao** [comment]
Thank you. I noticed some of the packages in the requirements.txt for the
manuscript branch aren't pinned, so on newer installs it causes conflicts.
I pip freeze'd a working environment and I'll reply with a fixed
requirements.txt soon.
