### ISSUE TITLE
Error when running verification model

### ISSUE THREAD

**Issue by ashishkab0b** [Stanford-STAGES/stanford-stages#7]
I am running into an error when running the verification script with the CHP040.edf data. 

```
Traceback (most recent call last):
  File "inf_narco_app.py", line 305, in <module>
    main(edfFile, jsonObj)
  File "inf_narco_app.py", line 127, in main
    print(narcoApp.get_diagnosis())
  File "inf_narco_app.py", line 188, in get_diagnosis
    prediction = self.get_narco_prediction()
  File "inf_narco_app.py", line 246, in get_narco_prediction
    os.path.join(gpmodels_base_path, gpmodel, gpmodel + '_fold{:02}.gpm'.format(k + 1)))
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/saver.py", line 42, in load
    return CoderDispatcher(context).decode(encoded_target)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 616, in decode
    return self._execute_coder(item, 'decode')
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 608, in _execute_coder
    return coder(self.context).decode(item)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 419, in decode
    variables = self._decode_attributes(item)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 442, in _decode_attributes
    return CoderDispatcher(self.context).decode(data)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 616, in decode
    return self._execute_coder(item, 'decode')
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 608, in _execute_coder
    return coder(self.context).decode(item)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 302, in decode
    return {k : dispatcher.decode(data[k]) for k in data.dtype.fields.keys()}
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 302, in <dictcomp>
    return {k : dispatcher.decode(data[k]) for k in data.dtype.fields.keys()}
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 616, in decode
    return self._execute_coder(item, 'decode')
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 608, in _execute_coder
    return coder(self.context).decode(item)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 420, in decode
    return self._decode_object(item, variables)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/saver/coders.py", line 559, in _decode_object
    instance.compile(session=self.context.session)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/core/node.py", line 58, in compile
    self.build()
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/core/node.py", line 156, in build
    self._build()
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/params/parameterized.py", line 295, in _build
    param.build()
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/core/node.py", line 156, in build
    self._build()
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/params/parameter.py", line 363, in _build
    unconstrained = self._build_parameter()
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/params/parameter.py", line 388, in _build_parameter
    args = dict(trainable=self.trainable)
  File "/Users/ashish/files/sber/stanford-stages/env/lib/python3.7/site-packages/gpflow/params/parameter.py", line 251, in trainable
    return self._trainable
AttributeError: 'Parameter' object has no attribute '_trainable'
```

I don't quite know where to go from here, but would really appreciate some suggestions!
Thank you.

**Comment by ashishkab0b** [comment]
Fixed this by installing a previous version of gpflow (1.2.0 instead of 1.3.0)
